// Generated by unplugin-env-parsing
export {}
declare global {
  interface ImportMetaEnv {

  }
  namespace NodeJS {
    interface ProcessEnv {
      readonly 'ALLUSERSPROFILE': string
      readonly 'APPDATA': string
      readonly 'COLOR': number
      readonly 'CommonProgramW6432': string
      readonly 'COMPUTERNAME': string
      readonly 'ComSpec': string
      readonly 'DriverData': string
      readonly 'EDITOR': string
      readonly 'HOME': string
      readonly 'HOMEDRIVE': string
      readonly 'HOMEPATH': string
      readonly 'INIT_CWD': string
      readonly 'LOCALAPPDATA': string
      readonly 'LOGONSERVER': string
      readonly 'NODE': string
      readonly 'NODE_ENV': string
      readonly 'NUMBER_OF_PROCESSORS': number
      readonly 'OneDrive': string
      readonly 'OneDriveConsumer': string
      readonly 'OS': string
      readonly 'Path': string
      readonly 'PATHEXT': string
      readonly 'PROCESSOR_ARCHITECTURE': string
      readonly 'PROCESSOR_IDENTIFIER': string
      readonly 'PROCESSOR_LEVEL': number
      readonly 'PROCESSOR_REVISION': string
      readonly 'ProgramData': string
      readonly 'ProgramW6432': string
      readonly 'PROMPT': string
      readonly 'PSModulePath': string
      readonly 'PUBLIC': string
      readonly 'SESSIONNAME': string
      readonly 'SystemDrive': string
      readonly 'SystemRoot': string
      readonly 'TEMP': string
      readonly 'TMP': string
      readonly 'USERDOMAIN': string
      readonly 'USERDOMAIN_ROAMINGPROFILE': string
      readonly 'USERNAME': string
      readonly 'USERPROFILE': string
      readonly 'windir': string
      readonly 'WSLENV': string
      readonly 'WT_PROFILE_ID': string
      readonly 'WT_SESSION': string
      readonly 'ZES_ENABLE_SYSMAN': number
    }
  }
}